[package]
name = "mem"
version = "0.1.0"
edition = "2024"

[features]
alloc = []
bump = ["alloc"]
linked-list = ["alloc"]

[dependencies]
bitflags = "2.6.0"
thiserror = { version = "2.0.12", default-features = false }
